---
- hosts: localhost
  tasks: 
  - name: render hv-spray template
    template: src=/opt/winspray/current/infra.yaml dest=/opt/winspray/current/infra.yaml.rendered
    delegate_to: localhost
  - name: include now rendered infra
    include_vars: 
      file: /opt/winspray/current/infra.yaml.rendered
  - name: create vagrant env
    template: src=/winspray/playbooks/templates/vagrant.vars.rb.j2 dest=/opt/winspray/current/vagrant.vars.rb
    delegate_to: localhost
  - name: create hosts inventory
    template: src=/winspray/playbooks/templates/hosts.yaml.j2 dest=/opt/winspray/current/hosts.yaml
    delegate_to: localhost
