- hosts: kube-master[0]
  tasks:
  - name: Get credentials
    fetch:
      src:  "/root/.kube/config"
      dest: "/opt/winspray/"
    tags:
      - kube_config

  - name: copy to root dir
    copy:
      src: /opt/winspray/{{ inventory_hostname }}/root/.kube/config
      dest: /opt/winspray/current/kube-config
    delegate_to: localhost
    tags:
      - kube_config

  - name: replace with masters FQDN for connection from management interface
    replace:
      path: /opt/winspray/current/kube-config
      regexp: '(\s+)server: .*$'
      replace: '\1server: https://{{ inventory_hostname }}:6443'
    delegate_to: localhost
    tags:
      - kube_config

  - name: Remove old fetched file
    file:
      path: "/opt/winspray/{{ inventory_hostname }}"
      state: absent
    delegate_to: localhost
    tags:
      - kube_config

  - name: Copy Dashboard Service Account yaml
    copy:
      src: /winspray/playbooks/files/dashboard-svc-role.yml
      dest:  /etc/kubernetes
    tags:
      - dashboard

  - name: Create Service account
    shell:
      cmd: /usr/local/bin/kubectl apply -f /etc/kubernetes/dashboard-svc-role.yml
      warn: false
    tags:
      - dashboard

  - name: Get token
    shell:
      cmd: /usr/local/bin/kubectl -n kube-system describe secret $(/usr/local/bin/kubectl -n kube-system get secret | grep dashboard-admin-user | awk '{print $1}') | grep 'token:' | cut -d ':' -f 2
      warn: false
    register: token_dashboard
    tags:
      - dashboard

  - name: dump dashboard token in a file
    lineinfile:
      line: "{{ token_dashboard.stdout }}"
      dest: "/opt/winspray/current/dashboard-token"
      create: yes
    delegate_to: localhost
    tags:
      - dashboard
